### ISSUE TITLE
消费者每次只能接受到发送消息的四分之一

### ISSUE THREAD

**Issue by aywangchen** [maihaoche/rocketmq-spring-boot-starter#14]
每次消费者都只能接收到发送消息的四分之一，并且序号都是间隔3；因为每个topic默认是初始化4个队列，怀疑是不是只是从一个队列里去接受消息；
用官方demo跑了一下，消息是能全部获取到的;
是不是在哪里有特殊的配置？

**Comment by suclogger** [comment]
@aywangchen 感谢反馈。能否贴一下您的代码实现？

**Comment by aywangchen** [comment]
感谢您的回复，应该是我程序自身的问题，重写之后没有再出现上述问题；

**Comment by aywangchen** [comment]
@suclogger 感谢您的回复，应该是我程序的问题，重写之后没有再出现上述现象；还有个问题不知道您是否了解，我们配置了Rocket-MQ-Console，发送一条消息，然后再消费这条消息，在驾驶舱的Broker TOP 10的统计界面中新增的消息数量为2条，如果只发送但不消费，统计的消息数量就是1条。这种情况是否是正常的

**Comment by suclogger** [comment]
@aywangchen 如果开启了消费追溯（默认开启），会投递一条消费的消费情况到topic：MQ_TRACE_DATA，详见：[wiki](https://github.com/maihaoche/rocketmq-spring-boot-starter/wiki/%E8%BF%BD%E6%BA%AF%E6%B6%88%E6%81%AF%E6%B6%88%E8%B4%B9)

**Comment by aywangchen** [comment]
@suclogger 了解了，非常感谢！
