### ISSUE TITLE
RocketMq消息轨迹的问题

### ISSUE THREAD

**Issue by SoftwareKing** [maihaoche/rocketmq-spring-boot-starter#19]
@suclogger 您好，关于消息轨迹的几个疑惑点，方便加微信沟通一下吗？我的微信是Software_King，期待您的回复。

- 问个问题哈：RocketMq消息轨迹只能通过这个org.apache.rocketmq.client.hook.ConsumeMessageHook去实现吗？，自己实现consumeMessageBefore和consumeMessageAfter

- 如果要实现从Producer到Broker，再到Consumer的消息轨迹，有接口吗？

**Comment by suclogger** [comment]
Not an issue.
