### ISSUE TITLE
同步刷盘timeout，项目是进行重新推送,但doAfterSyncSend却没有消息的内容无法重新推送

### ISSUE THREAD

**Issue by belugaliu** [maihaoche/rocketmq-spring-boot-starter#5]
我们想用rocketMQ的消息为任务，推送其他服务消费任务指令。所以我们可能丢不起。所以，配置rocketMQ为SYNC_FLUSH.<br>
SYNC_FLUSH的SendStatus有对应几个状态:SEND_OK、FLUSH_DISK_TIMEOUT、FLUSH_SLAVE_TIMEOUT、SLAVE_NOT_AVAILABLE<br>
对于状态是FLUSH_DISK_TIMEOUT和FLUSH_SLAVE_TIMEOUT是需要重推的，但是给的业务后续处理的方法只有SendResult没有Message参数，是不是可以改一下,满足要求？
```java
  /**
     * 重写此方法处理发送后的逻辑
     *
     * @param sendResult  发送结果
     */
    public void doAfterSyncSend(SendResult sendResult) {}
```

**Comment by suclogger** [comment]
@liuliliGithub 刚才提交的内容是我们内部的版本，回调参数使用的是rocketmq的Message，如果需要使用原来的消息体POJO，可以稍加改造一下。

**Comment by belugaliu** [comment]
好的，谢谢
