### ISSUE TITLE
建议可通过配置设置VipChannelEnabled

### ISSUE THREAD

**Issue by Echelon77** [maihaoche/rocketmq-spring-boot-starter#6]
rocketmq服务端3.2.6版本（或许其他也有类似情况），在producer和consumer连接时连接的是vip端口，导致发送、启动失败；建议在MQProducerAutoConfiguration 和MQConsumerAutoConfiguration中对producer和consumer进行配置参数读取并设置VipChannelEnabled的，以便通过配置即可对低版本服务端的支持

**Comment by Echelon77** [comment]
搞定！
可以在JVM里设置参数-Dcom.rocketmq.sendMessageWithVIPChannel=false来解决
看了下maven的dependency:tree，该项目依赖rocketmq 4.0，还无法替换成低版本3.x；原因是3.x包名是alibaba捐献前的，4.x是apache的。
但最好还是能提供一个设置VipChannelEnabled的配置参数比较好

**Comment by suclogger** [comment]
配置已经添加，请更新版本到 0.0.6

**Comment by xuli1266** [comment]
MQProducerAutoConfiguration中已经添加，但是MQConsumerAutoConfiguration.publishConsumer中还是没有加上vip参数.
0.0.6版本consumer jvm参数中依然添加-Dcom.rocketmq.sendMessageWithVIPChannel=false来解决

**Comment by suclogger** [comment]
@xuli1266 
感谢反馈，确实遗漏了，我推送了新的代码，可以帮忙review一下吗 #8aa7e391

**Comment by xuli1266** [comment]
0.0.7已经可以了

**Comment by ijaychang** [comment]
VipChannelEnabled还没用到过。。。

**Comment by suclogger** [comment]
@jaychang9 3.5.8版本以后是默认启用的，这个配置项是为了兼容老版本。
